# -*- coding: utf-8 -*-
"""Python_Zero_to_One.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNasWJhz2wRr60wdcHKkFpbpfwWc6SwJ
"""

"""Mini Reto Guiado: Rompecabezas de Sintaxis"""

print("Estoy aprendiendo Python");
print("Hola");
print("Mi nombre es Carlos");

"""**1. Imprimir tu *nombre***"""



"""**2. Imprimir tu edad (usando números)**"""



"""
**3. Imprimir el nombre de tu ciudad**
"""



"""**4. Imprimir tu comida favorita**"""



"""**5. Imprimir tres líneas de texto distintas**"""



"""**6. Imprimir 5 líneas de texto diferentes**"""



"""**7. Imprimir el mensaje**"""



"""**8. Imprimir una frase de motivación personal**"""



"""**9. Imprimir una frase combinada con un número**"""



"""**10. Mini perfil**"""

